### ISSUE TITLE
Doesn't show the logs

### ISSUE THREAD

**Issue by pavliukpetro** [mihai-vlc/bm-extender#2]
Hello, the extension doesn't show the log. I see the js error in the console.
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at Object.formatObjects (content.js:2)
    at l (content.js:2)
    at u (content.js:2)
    at Object.d [as setupLog] (content.js:2)
    at content.js:2

Please, fix.
Thank you.

**Comment by MMoserM** [comment]
Just adding to this, the issue is caused when DWithEase extension is enabled (https://chrome.google.com/webstore/detail/ffhabonelknmejmdnekedmijlhebpcio), when i disabled DWtihEase on my browser it went back to working

**Comment by mihai-vlc** [comment]
This is now fixed in 1.7.5

Please reopen the ticket if you still have issues.

**Comment by pavliukpetro** [comment]
Thank you, @ionutvmi
