### ISSUE TITLE
No longer works on custom domains.

### ISSUE THREAD

**Issue by prutins** [mihai-vlc/bm-extender#8]
Error loading the extension when used on a site with a custom hostname.  "Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension."  Fails for both .js and .css files.

Submitted a PR for it, though I admit I haven't tested the code.  Just trusting that the fix is the same as last time because the content team is complaining again! :)

**Comment by mihai-vlc** [comment]
This change has been published in v2.3.0
It should show in the web store in a few hours.

Please try it out and reopen this issue if any additional feedback is needed.
